# Generated by Django 5.2.7 on 2026-05-13 00:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('electrico', 'Eléctrico'), ('plomeria', 'Plomería'), ('construccion', 'Construcción'), ('ferreteria', 'Ferretería'), ('limpieza', 'Limpieza'), ('tecnologia', 'Tecnología'), ('otro', 'Otro')], max_length=30)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('rollo', 'Rollo')], max_length=20)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario Base'), ('gestor', 'Gestor'), ('guardia', 'Guardia'), ('mantencion', 'Mantención')], default='usuario', max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('vinculo', models.CharField(blank=True, choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('funcionario', 'Funcionario')], max_length=20, null=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('jornada', models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina'), ('mixta', 'Mixta')], max_length=15, null=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_cuenta', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('motivo', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('permiso', 'Permiso Administrativo'), ('capacitacion', 'Capacitación'), ('vacaciones', 'Vacaciones'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inasistencias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trabajo', models.TextField()),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('horas_hombre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foto_final', models.ImageField(blank=True, null=True, upload_to='mantencion/fotos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='app.material')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados', to='app.registromantencion')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('en_proceso', 'En Proceso'), ('en_validacion', 'En Validación (Guardia)'), ('en_mantencion', 'En Mantención'), ('pausado', 'Pausado'), ('no_reparado', 'No Reparado – Rectificar'), ('cerrado', 'Cerrado'), ('eliminado', 'Eliminado')], default='enviado', max_length=30)),
                ('estado_pausa', models.CharField(blank=True, choices=[('material', 'Falta de Material'), ('personal', 'Falta de Personal'), ('nivel_mayor', 'Requiere Nivel Mayor'), ('externalizacion', 'Requiere Externalización')], max_length=20, null=True)),
                ('motivo_pausa', models.TextField(blank=True, null=True)),
                ('comentario_reactivacion', models.TextField(blank=True, null=True)),
                ('edificio_texto', models.CharField(max_length=100)),
                ('piso_texto', models.CharField(max_length=10)),
                ('sala_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_sala', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('taller', 'Taller'), ('baño', 'Baño'), ('pasillo', 'Pasillo'), ('oficina', 'Oficina'), ('area_comun', 'Área Común'), ('otro', 'Otro')], default='aula', max_length=20)),
                ('id_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_sala', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('electrico', 'Eléctrico'), ('plomeria', 'Plomería'), ('infraestructura', 'Infraestructura'), ('climatizacion', 'Climatización'), ('tecnologia', 'Tecnología'), ('accesibilidad', 'Accesibilidad'), ('mobiliario', 'Mobiliario'), ('otro', 'Otro')], max_length=30)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('afecta_clase', models.BooleanField(default=False)),
                ('riesgo_electrico', models.BooleanField(default=False)),
                ('riesgo_estructural', models.BooleanField(default=False)),
                ('riesgo_accesibilidad', models.BooleanField(default=False)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='tickets/evidencia/')),
                ('id_activo_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cerrado_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('gestor_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_gestionados', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mantencion', to='app.ticket'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ticket_enviado', 'Ticket Enviado'), ('ticket_cerrado', 'Ticket Cerrado'), ('asignacion', 'Asignación'), ('validacion', 'Validación'), ('pausa', 'Pausa'), ('reactivacion', 'Reactivación'), ('no_reparado', 'No Reparado'), ('inasistencia', 'Inasistencia'), ('cuenta_solicitud', 'Solicitud de Cuenta'), ('cuenta_aprobada', 'Cuenta Aprobada'), ('cuenta_rechazada', 'Cuenta Rechazada'), ('reset_password', 'Recuperación de Contraseña'), ('general', 'General')], max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('url_accion', models.CharField(blank=True, max_length=300, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('archivada', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoReparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_tecnico', models.TextField()),
                ('material_requerido', models.TextField()),
                ('criticidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('requiere_externalizacion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_reparable', to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('es_interno', models.BooleanField(default=False)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(default='ticket', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=100)),
                ('piso', models.CharField(max_length=10)),
                ('sala', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('taller', 'Taller'), ('baño', 'Baño'), ('pasillo', 'Pasillo'), ('oficina', 'Oficina'), ('area_comun', 'Área Común'), ('otro', 'Otro')], max_length=20)),
                ('id_sap', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sede', 'edificio', 'piso', 'sala'],
                'unique_together': {('sede', 'edificio', 'piso', 'sala')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.ubicacion'),
        ),
        migrations.CreateModel(
            name='ValidacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('valido', 'Válido'), ('invalido', 'Inválido')], max_length=10)),
                ('comentario', models.TextField()),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='validaciones/')),
                ('checklist_electrico', models.BooleanField(default=False)),
                ('checklist_estructural', models.BooleanField(default=False)),
                ('checklist_accesibilidad', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacion', to='app.ticket')),
            ],
        ),
    ]
