# Generated by Django 5.2.7 on 2026-05-13 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noreparable',
            name='costo_estimado_externo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='noreparable',
            name='empresa_externa_sugerida',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noreparable',
            name='foto_diagnostico',
            field=models.ImageField(blank=True, null=True, upload_to='no_reparable/'),
        ),
        migrations.AddField(
            model_name='noreparable',
            name='herramientas_faltantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noreparable',
            name='personal_especializado_requerido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noreparable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='herramientas_utilizadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='personal_adicional_requerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='reparacion_exitosa',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='requiere_nivel_mayor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='tiempo_total_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromantencion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='validacionguardia',
            name='evidencia_obligatoria_presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validacionguardia',
            name='tiempo_validacion_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validacionguardia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ActualizacionEstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('razon', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='app.ticket')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creaci?n'), ('asignacion', 'Asignaci?n'), ('reasignacion', 'Reasignaci?n'), ('cambio_estado', 'Cambio de Estado'), ('validacion', 'Validaci?n (Guardia)'), ('rechazo_validacion', 'Rechazo Validaci?n'), ('inicio_mantencion', 'Inicio Mantenci?n'), ('completar_mantencion', 'Reparaci?n Completada'), ('no_reparable', 'Marcado No Reparable'), ('reactivacion', 'Reactivaci?n'), ('pausa', 'Pausa'), ('cierre', 'Cierre'), ('vinculacion_activo', 'Vinculaci?n a Activo'), ('comentario', 'Comentario'), ('comentario_interno', 'Comentario Interno'), ('derivacion', 'Derivaci?n'), ('reasignacion_por_inasistencia', 'Reasignaci?n por Inasistencia')], max_length=30)),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_acciones', to='app.ticket')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reasignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reasignados_a_este', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialesFaltantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('solicitado', 'Solicitado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='app.material')),
                ('registro_mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_faltantes', to='app.registromantencion')),
            ],
        ),
    ]
