# Generated by Django 5.2.7 on 2026-06-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiontrabajo',
            name='herramientas_utilizadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
