# Generated by Django 5.2.7 on 2026-06-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transicionestado',
            name='rol_requerido',
            field=models.CharField(blank=True, choices=[('usuario', 'Usuario Base'), ('gestor', 'Gestor'), ('guardia', 'Guardia'), ('mantencion', 'Mantención')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario Base'), ('gestor', 'Gestor'), ('guardia', 'Guardia'), ('mantencion', 'Mantención')], default='usuario', max_length=20),
        ),
    ]
