# Generated by Django 5.2.7 on 2026-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sesiontrabajo_herramientas_utilizadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromantencion',
            name='herramientas_utilizadas',
        ),
        migrations.RemoveField(
            model_name='registromantencion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='registromantencion',
            name='personal_adicional_requerido',
        ),
        migrations.RemoveField(
            model_name='registromantencion',
            name='requiere_nivel_mayor',
        ),
        migrations.AddField(
            model_name='sesiontrabajo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesiontrabajo',
            name='personal_adicional_requerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesiontrabajo',
            name='requiere_nivel_mayor',
            field=models.BooleanField(default=False),
        ),
    ]
