# Generated by Django 5.2.7 on 2026-05-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_noreparable_costo_estimado_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='inicio_trabajo_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
