# Generated by Django 5.2.7 on 2026-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_inicio_trabajo_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('en_proceso', 'En Proceso'), ('en_validacion', 'En Validación (Guardia)'), ('validado', 'Validado por Seguridad'), ('en_mantencion', 'En Mantención'), ('reparado', 'Reparado – Pendiente cierre'), ('pausado', 'Pausado'), ('no_reparado', 'No Reparado – Escalar'), ('cerrado', 'Cerrado'), ('eliminado', 'Eliminado')], default='enviado', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado_pausa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
