# Generated by Django 5.2.13 on 2026-05-20 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estado_pausa_multi_y_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacciones',
            name='es_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historialacciones',
            name='sub_estado_nuevo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cancelado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sub_estado',
            field=models.CharField(blank=True, choices=[('pendiente_revision', 'Pendiente de Revisión'), ('revisado', 'Revisado'), ('asignado_mantencion', 'Asignado a Mantención'), ('escalado', 'Escalado a Externo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialacciones',
            name='tipo_accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('asignacion', 'Asignación'), ('reasignacion', 'Reasignación'), ('cambio_estado', 'Cambio de Estado'), ('validacion', 'Validación (Guardia)'), ('rechazo_validacion', 'Rechazo Validación'), ('inicio_mantencion', 'Inicio Mantención'), ('completar_mantencion', 'Reparación Completada'), ('no_reparable', 'Marcado No Reparable'), ('reactivacion', 'Reactivación'), ('pausa', 'Pausa'), ('cierre', 'Cierre'), ('cancelacion', 'Cancelación'), ('revocacion', 'Revocación'), ('vinculacion_activo', 'Vinculación a Activo'), ('comentario', 'Comentario'), ('comentario_interno', 'Comentario Interno'), ('derivacion', 'Derivación'), ('reasignacion_por_inasistencia', 'Reasignación por Inasistencia')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('en_proceso', 'En Proceso'), ('en_validacion', 'En Validación (Guardia)'), ('validado', 'Validado por Seguridad'), ('en_mantencion', 'En Mantención'), ('reparado', 'Reparado – Pendiente cierre'), ('pausado', 'Pausado'), ('no_reparado', 'No Reparado – Escalar'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado'), ('revocado', 'Revocado'), ('eliminado', 'Eliminado')], default='enviado', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario Base'), ('gestor', 'Gestor'), ('enc_seguridad', 'Encargado de Seguridad'), ('guardia', 'Guardia'), ('mantencion', 'Mantención')], default='usuario', max_length=20),
        ),
        migrations.CreateModel(
            name='AsignacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_asignacion', models.CharField(choices=[('guardia', 'Guardia'), ('mantencion', 'Mantención')], max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='app.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.DeleteModel(
            name='ActualizacionEstadoTicket',
        ),
    ]
