# Generated by Django 5.2.7 on 2026-07-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_carrera_options_alter_carrera_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='app.ticket'),
        ),
        migrations.AlterField(
            model_name='sesiontrabajo',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='app.ticket'),
        ),
        migrations.AlterField(
            model_name='validacionguardia',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='validacion', to='app.ticket'),
        ),
    ]
