# Generated by Django 5.2.7 on 2026-06-03 12:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ticket_ubicacion_v3'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', app.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='estadocatalogo',
            name='uq_estado_entidad_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='transicionestado',
            name='uq_transicion_estados',
        ),
        migrations.AddField(
            model_name='usuario',
            name='auth0_sub',
            field=models.CharField(blank=True, help_text='Identificador único del usuario en Auth0. Se asigna automáticamente al registrar vía Auth0.', max_length=120, null=True, unique=True, verbose_name='Auth0 Subject ID'),
        ),
        migrations.AlterUniqueTogether(
            name='estadocatalogo',
            unique_together={('entidad', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='transicionestado',
            unique_together={('estado_origen', 'estado_destino')},
        ),
    ]
