# Generated by Django 5.2.7 on 2026-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_auth0_sub_to_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionticket',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha en la que se debe realizar la validación o el trabajo asignado', null=True, verbose_name='Fecha programada'),
        ),
    ]
