# Generated by Django 5.2.7 on 2026-06-12 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_especialidad_remove_usuario_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especialidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
            ],
            options={
                'verbose_name': 'Especialidad de Material',
                'verbose_name_plural': 'Especialidades de Materiales',
                'unique_together': {('material', 'especialidad')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Especialidades que están autorizadas a ver y usar este material en sus reportes.', related_name='materiales', through='app.EspecialidadMaterial', to='app.especialidad'),
        ),
    ]
