# Generated by Django 5.2.7 on 2026-06-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transicionestado_rol_requerido_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionticket',
            unique_together={('ticket', 'usuario', 'rol_asignacion')},
        ),
    ]
